<?php

const USER_STATUS_NON_ACTIVE = 0;
const USER_STATUS_ACTIVE = 1;
const USER_STATUS_RESTRICTED = 2;

const FORM_REVIEW_NOT_APPLICANT = 0;
const FORM_REVIEW_PENDING = 1;
const FORM_REVIEW_ACCEPTED = 2;
const FORM_REVIEW_REJECTED = 3;
const FORM_REVIEW_WAITING_LIST = 4;

const TOPUP_PENDING = 0;
const TOPUP_APPROVED = 1;
const TOPUP_REJECTED = 2;

const COST_SPENDING_0 = 0;
const COST_SPENDING_1 = 1;
const COST_SPENDING_2 = 2;
const COST_SPENDING_3 = 3;
const COST_SPENDING_4 = 4;

const EMAIL_VERIFICATION_PENDING = 0;
const EMAIL_VERIFICATION_SUCCESS = 1;

const VERIFICATION_EMAIL_TYPE = 0;
const VERIFICATION_FORGOT_PASSWORD_TYPE = 1;

const ACCOUNT_WHATSAPP = 0;
const ACCOUNT_TELEGRAM = 1;

const NOTIF_NOT_READ = 0;
const NOTIF_READ = 1;

const REFUND_USER_PENDING = 0;
const REFUND_USER_APPROVED = 1;
const REFUND_USER_REJECTED = 2;

const STATUS_TICKET_PENDING = 0;
const STATUS_TICKET_IN_PROGRESS = 1;
const STATUS_TICKET_FINISHED = 2;

const TICKET_PRIORITY_LOW = 0;
const TICKET_PRIORITY_MEDIUM = 1;
const TICKET_PRIORITY_HIGH = 2;
